name: mpi.cr CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        vendor: [mpich, openmpi]
        version: [3.3, 3.2.1, 3.0.4, 3.1.4, 4.0.1]
        exclude:
          - vendor: mpich
            version: 4.0.1
          - vendor: mpich
            version: 3.1.4
          - vendor: mpich
            version: 3.0.4
          - vendor: openmpi
            version: 3.3
          - vendor: openmpi
            version: 3.2.1

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: cache-dep
        with:
          path: ${GITHUB_WORKSPACE}/${{ matrix.vendor }}-${{ matrix.version }}
          key: ${{ matrix.vendor }}-${{ matrix.version }}

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: |
          apt update
          export MPI_PREFIX="${GITHUB_WORKSPACE}/${{ matrix.vendor }}-${{ matrix.version }}"
          export MPI_LIBRARY="${{ matrix.vendor }}"
          export MPI_LIBRARY_VERSION="${{ matrix.version }}"
          apt-get -yq --no-install-suggests --no-install-recommends install build-essential gfortran wget
          ci/install-mpi.sh

      - name: Run tests
        run: |
          export MPI_PREFIX="${GITHUB_WORKSPACE}/${{ matrix.vendor }}-${{ matrix.version }}"
          export PATH="${MPI_PREFIX}/bin:${PATH}"
          export LD_LIBRARY_PATH="${MPI_PREFIX}/lib:${LD_LIBRARY_PATH}"
          export LIBRARY_PATH="${MPI_PREFIX}/lib:${LIBRARY_PATH}"
          make
          make spec no-debug=1
