name: mpi.cr CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        vendor: [mpich, openmpi]
        version: [3.3, 3.2.1, 3.0.4, 3.1.4, 4.0.1]
        exclude:
          - vendor: mpich
            version: 4.0.1, 3.1.4, 3.0.4
          - vendor: openmpi
            version: 3.3, 3.2.1
     
    container:
      image: crystallang/crystal
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: | 
        sudo apt update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential gfortran
        sh ci/install-mpi.sh
        export MPI_PREFIX="${HOME}/opt/${{ matrix.vendor }}-${{ matrix.version }}"
        export PATH="${HOME}/.local/bin:${MPI_PREFIX}/bin${PATH:+":${PATH}"}"
        export LD_LIBRARY_PATH=${MPI_PREFIX}/lib:${LD_LIBRARY_PATH}
        export LIBRARY_PATH=${MPI_PREFIX}/lib:${LIBRARY_PATH}
        make
    - name: Run tests
      run: make spec no-debug=1
